class Constants:
    EVENT_SCRIPT_DEFINITIONS = [
        # Init
        {
            "name": "init.sqf", 
            "description": "Executed when mission is started (before briefing screen).", 
            "params": []
        },
        {
            "name": "init3DEN.sqf",
            "description": "Executed when loading a scenario in Eden Editor if the file is present. Useful for executing scenario-specific editor functionality.",
            "params": []
        },
        {
            "name": "initIntro.sqf",
            "description": "Executed when intro, outro win or outro lose is started.",
            "params": []
        },
        {
            "name": "initPlayerLocal.sqf",
            "description": "Executed locally when player joins mission (includes both mission start and JIP). See [Initialisation Order](https://community.bistudio.com/wiki/Initialisation_Order) for details about when exactly the script is executed.",
            "params": ["_player", "_didJIP"]
        },
        {
            "name": "initPlayerServer.sqf",
            "description": "Executed only on server when a player joins mission (includes both mission start and JIP). See [Initialisation Order](https://community.bistudio.com/wiki/Initialisation_Order) for details about when exactly the script is executed. This script relies on BIS_fnc_execVM and remoteExec. If CfgRemoteExec's class Functions is set to mode = 0 or 1, the script will never be executed. Therefore, initPlayerServer.sqf should be avoided - use this method instead.",
            "params": ["_playerUnit", "_didJIP"]
        },
        {
            "name": "initServer.sqf",
            "description": "Executed only on server when mission is started. See Initialisation Order for details about when exactly the script is executed.",
            "params": []
        },
        # Player / respawn (wiki: several are multiplayer-only)
        {
            "name": "onPlayerKilled.sqf",
            "description": "Executed when player is killed in singleplayer or in multiplayer mission.",
            "params": ["_oldUnit", "_killer", "_respawn", "_respawnDelay"]
        },
        {
            "name": "onPlayerRespawn.sqf",
            "description": "Executed locally when player respawns in a multiplayer mission. This event script will also fire at the beginning of a mission if respawnOnStart is 0 or 1, oldUnit will be objNull in this instance. This script will not fire at mission start if respawnOnStart equals -1.",
            "params": ["_newUnit", "_oldUnit", "_respawn", "_respawnDelay"]
        },
        # Other
        {
            "name": "exit.sqf",
            "description": "Executed when mission is finished (before debriefing screen). In Arma 3, see also Ended and MPEnded Mission Event Handlers.",
            "params": ["_endType"]
        },
        {
            "name": "missionFlow.fsm",
            "description": "Executed on post-init when mission is started. See [BIS_fnc_missionFlow](https://community.bistudio.com/wiki/BIS_fnc_missionFlow).",
        },
        {
            "name": "onFlare.sqs",
            "description": "Executed when a flare is lit after being fired from grenade launcher.",
            "params": ["_colorRGB", "_shooter", "_projectile", "_instigator"]
        },
        {
            "name": "teamSwitchScript.sqs",
            "description": "Executed after a [Team Switch](https://community.bistudio.com/wiki/Team_Switch) is done. Not triggered by selectPlayer.",
            "params": ["_oldUnit", "_newUnit"]
        }
    ]
    GENERATED_CODE_TEMPLATE = """/**
    --This file was generated by A3 Launchpad.--
    Do not edit this file manually unless you know what you are doing.
    ------------------------------------------------------------------
    Author: $author
    File: $fileName
    Time: $generationTime
*/
"""

    EXT_TEMPLATE = {
        "header": {
            "gameType": "CTI",
            "minPlayers": 1,
            "maxPlayers": 64,
        },
        "difficultyOverride": {
            "tacticalPing": 0,
        },
        "author": "\"$author\"",
        "onLoadName": "\"$onLoadName\"",
        "briefingName": "\"$briefingName\"",
        "loadScreen": "\"$loadScreen\"",
        "cba_settings_hasSettingsFile": 0,
        "saving": 0,
        "taskManagement_markers3D": 1,
        "allowSubordinatesTakeWeapons": 1,
        "respawn": 3,
        "respawnButton": 1,
        "respawnDelay": 0,
        "respawnVehicleDelay": 120,
        "reviveMode": 2,
        "reviveUnconsciousStateMode": 2,
        "briefing": 0,
        "debriefing": 0,
        "skipLobby": 0,
        "disabledAI": 1,
        "aiKills": 1,
        "enableDebugConsole": 1,
        "enableTeamSwitch": 0,
        "joinUnassigned": 1,
        "onCheat": "\"hint str _this\"",
        "forceRotorLibSimulation": 1,
        "corpseManagerMode": 1,
        "corpseLimit": 25,
        "corpseRemovalMinTime": 300,
        "corpseRemovalMaxTime": 1200,
        "weaponholderManagerMode": 3,
        "weaponholderLimit": 25,
        "weaponholderRemovalMinTime": 120,
        "weaponholderRemovalMaxTime": 300,
        "wreckManagerMode": 1,
        "wreckLimit": 5,
        "wreckRemovalMinTime": 300,
        "wreckRemovalMaxTime": 300,
        "disposalCheckPeriod": 30,
        "minPlayerDistance": [ # metres. Default: { 0, 0, 0, -1, -1, -1 }
            50,		60,		70,		# corpsesMinDist,		wrecksMinDist,		weaponholdersMinDist
            300,	120,	60		# corpsesOverrideTime,	wrecksOverrideTime,	weaponholdersOverrideTime
        ]
    }

    SQM_TEMPLATE = """version=54;
class EditorData
{
	moveGridStep=1;
	angleGridStep=0.2617994;
	scaleGridStep=1;
	autoGroupingDist=10;
	toggles=2;
	class Camera
	{
		pos[]={1796.5475,6.5295224,2826.6296};
		dir[]={-0.11685842,-0.18468618,-0.97582537};
		up[]={-0.021959899,0.9827975,-0.18337597};
		aside[]={-0.99290574,0,0.11890386};
	};
};
binarizationWanted=$binarizationWanted;
sourceName="default";
class AddonsMetaData
{
};
randomSeed=$randomSeed;
class ScenarioData
{
	author="$author";
};
"""

    MANAGED_SCENARIOS_TEMPLATE = {
    "name": "Example Scenario",
    "map_suffix": "vr",
    "description": "This is an example scenario.",
    "author": "Example Author",
    "mission_type": "mp",
    "generate_scripting_environment": False,
    "ext_params": {
        "header": {
            "gameType": "CTI",
            "minPlayers": 1,
            "maxPlayers": 64
        },
        "difficultyOverride": {
            "tacticalPing": 0
        },
        "author": "$author",
        "onLoadName": "$onLoadName",
        "briefingName": "$briefingName",
        "loadScreen": "$loadScreen",
        "cba_settings_hasSettingsFile": 0,
        "saving": 0,
        "taskManagement_markers3D": 1,
        "allowSubordinatesTakeWeapons": 1,
        "respawn": 3,
        "respawnButton": 1,
        "respawnDelay": 0,
        "respawnVehicleDelay": 120,
        "reviveMode": 2,
        "reviveUnconsciousStateMode": 2,
        "briefing": 0,
        "debriefing": 0,
        "skipLobby": 0,
        "disabledAI": 1,
        "aiKills": 1,
        "enableDebugConsole": 1,
        "enableTeamSwitch": 0,
        "joinUnassigned": 1,
        "onCheat": "hint str _this",
        "forceRotorLibSimulation": 1,
        "corpseManagerMode": 1,
        "corpseLimit": 25,
        "corpseRemovalMinTime": 300,
        "corpseRemovalMaxTime": 1200,
        "weaponholderManagerMode": 3,
        "weaponholderLimit": 25,
        "weaponholderRemovalMinTime": 120,
        "weaponholderRemovalMaxTime": 300,
        "wreckManagerMode": 1,
        "wreckLimit": 5,
        "wreckRemovalMinTime": 300,
        "wreckRemovalMaxTime": 300,
        "disposalCheckPeriod": 30,
        "minPlayerDistance": [
            50,
            60,
            70,
            300,
            120,
            60
        ]
    },
    "github_integration": False,
    "launch_mods": [],
}